version: "3.5"
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    networks:
      coherence:
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
    networks:
      coherence:
    image: grafana/grafana:8.5.27
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
    ports:
      - 3000:3000

  coherence1:
    hostname: machine1
    networks:
      coherence:
        aliases:
          - machine1
    image: ghcr.io/oracle/coherence-ce:22.09
    environment:
      - coherence.cluster=cluster1
      - coherence.member=member1
      - coherence.machine=machine1
      - coherence.metrics.http.enabled=true
      - coherence.wka=machine1
    ports:
      - 30000:30000
      - 20000:20000
      - 1408:1408
      - 9612:9612

  coherence2:
    hostname: machine2
    networks:
      coherence:
        aliases:
          - machine2
    image: ghcr.io/oracle/coherence-ce:22.09
    environment:
      - coherence.cluster=cluster1
      - coherence.member=member2
      - coherence.machine=machine1
      - coherence.metrics.http.enabled=true
      - coherence.wka=machine1
    ports:
      - 9613:9612

networks:
  coherence:
